apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: webapplication1-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webapplication1
  type: LoadBalancer
status:
  loadBalancer: {}