apiVersion: apps/v1
kind: Deployment
metadata:
  name: WebApplication1
spec:
  selector:
    matchLabels:
      app: WebApplication1
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: WebApplication1
    spec:
      containers:
      - name: WebApplication1
        image: yenne.azurecr.io/webapplication1:76
        ports:
        - containerPort: 80
